### ISSUE TITLE
[BUG] Recipe non valid: Similar genres (D)

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#16]
Errors with recipes have been corrected in version 5.1.2, but one error remains:

```
Recipe non valid: Similar genres (D)

	- Recipe contains non valid key: dyngenreWeight
	- Recipe contains non valid key: dyngenreRange
```

<details>
  <summary>Screenshots</summary>

![1](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/01cc30da-bef8-464b-bfad-4aebefeb409f)

![2](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/98b1379b-db76-4486-be9a-32e9bfdbed8b)

</details>

I checked with a new portable installation. I've also tried 'Restore defaults...' for the dynGenre tag.

In the [Similar genres (DYNGENRE)](https://github.com/regorxxx/Search-by-Distance-SMP/blob/main/presets/Search%20by/recipes/Similar%20genres%20(DYNGENRE).json) file, there's this:

```
{
	"name": "Similar genres (D)",
	"tags": {

(...)

		"dynGenre": {
			"weight": 40,
			"range": 2
		},

(...)

	},
	"scoreFilter": 70,
	"method": "DYNGENRE",
	"dyngenreWeight": 10,
	"dyngenreRange": 1
}
```

**Comment by regorxxx** [comment]
As the popup says, now the recipe is wrong. There is no need to reset tags. The last variables are obviously wrong, that's all.
Just delete them and done.

[Similar genres (DYNGENRE).json](https://github.com/regorxxx/Search-by-Distance-SMP/files/13384906/Similar.genres.DYNGENRE.json)

Not going to create another release for this, but will update the file on the next update. Thanks!

**Comment by username116** [comment]
Thank you for all these improvements.
