### ISSUE TITLE
[BUG] missing property (baseScore)

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#19]
I'm using the customizable search by distance button. I add a new custom tag. This message appears:

```
Error on tags settings.
To fix it, restore defaults on affected tags (customizable button) or globally (non-customizable buttons). These options are usually found by Shift + L. Clicking on the button. Then reload the panel.
If the error continues, report it as a bug.
------------------------------------------------------------------------
Tag missing property (baseScore): My tag name
```

<details><summary>Screenshots</summary>
<p>

![Screenshot](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/9b780221-10f1-4a8a-b3c8-9f9e0bc45808)

![Screenshot 2](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/810ebab3-0036-46c2-8cce-70eec6c1a8c6)

</p>
</details> 

I add a base score value and the messages disappear.
As this appears for each new custom tag, it seems that the default property is missing. Unless this is intentional.

**Comment by regorxxx** [comment]
Missed to add that key to new tags, glad I added tag checking in previous releases, this would have gone unnoticed otherwise for a long time.
