### ISSUE TITLE
[BUG] Readme not found

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#21]
I'm using the customizable search by distance button.

When I press Shift + click on the button to open the menu, the console says that the `shuffle_by_tags` readme file is missing.

```
Readme not found: D:\foobar-portable\profile\scripts\SMP\xxx-scripts\helpers\readme\shuffle_by_tags.txt
```

<details><summary>Screenshot</summary>
<p>

![1](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/d591277e-1a04-4ea6-b0c1-210e6e17efd5)

</p>
</details>

It's requested in the `buttons_sbd_menu_config.js` file on [this line](https://github.com/regorxxx/Search-by-Distance-SMP/blob/019cd9595ee998df41773aaadec82cdeff8b498a/buttons/helpers/buttons_sbd_menu_config.js#L986).

**Comment by regorxxx** [comment]
No new release until more important issues/features appear though.
