### ISSUE TITLE
[BUG] Small mistakes in the Readme files

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#23]
**Describe the bug**
I found two small errors in the Readme files: 
- in [search_by_distance_recipes_themes.txt](https://github.com/regorxxx/Search-by-Distance-SMP/blob/386912744b254e9a6ca6c4ebb5448bd123ad9ce2/helpers/readme/search_by_distance_recipes_themes.txt#L6), line 6: `buttons snd tools`,
- in [tags_global_remap.txt](https://github.com/regorxxx/Search-by-Distance-SMP/blob/386912744b254e9a6ca6c4ebb5448bd123ad9ce2/helpers/readme/tags_global_remap.txt#L2), line 2: `- Artist` is not aligned with its column.

**Comment by regorxxx** [comment]
This one was easy :) Thanks
