### ISSUE TITLE
[BUG] Custom tag names displayed incorrectly in the menu

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#24]
**Describe the bug**

Some words in custom tag names are displayed unexpectedly in the menu. I think this is due to a capitalization regular expression.

The words `Genre`, `Style` and `Region` display a slash or a space before them (screenshot 4).

**To Reproduce**

1. Load `buttons_toolbar.js`, then insert a search-by-distance customizable button with the menu. 
2. `Set Tags and weighting` > `New tag...`. Enter a name for the tag: `Genre 2`.
3. `Set Tags and weighting` > `New tag...`. Enter a name for the tag: `Style 2`.
4. `Set Tags and weighting` > `New tag...`. Enter a name for the tag: `Region 2` (screenshots 1, 2, 3).
5. In the menu, new slots have an extra slash or space at the beginning of the name (screenshot 4).

**Expected behavior**

Slot names should be displayed correctly in the menu, without an extra slash or space.

**Additional context**

<details><summary>Tags used for scoring (from panel properties)</summary>
<p>

```javascript
{
   "genre": {
      "weight": 15,
      "tf": ["GENRE"],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["string", "multiple", "graph"]
   },
   "style": {
      "weight": 15,
      "tf": ["STYLE"],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["string", "multiple", "graph"]
   },
   "dynGenre": {
      "weight": 15,
      "tf": [],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["number", "single", "virtual", "absRange"],
      "range": 1
   },
   "mood": {
      "weight": 10,
      "tf": ["MOOD"],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["string", "multiple", "combinations"],
      "combs": 6
   },
   "key": {
      "weight": 5,
      "tf": ["KEY"],
      "baseScore": 0,
      "scoringDistribution": "LOGARITHMIC",
      "type": ["string", "single", "keyMix", "keyRange"],
      "range": 3
   },
   "bpm": {
      "weight": 5,
      "tf": ["BPM"],
      "baseScore": 0,
      "scoringDistribution": "NORMAL",
      "type": ["number", "single", "percentRange"],
      "range": 50
   },
   "date": {
      "weight": 10,
      "tf": ["$year(%DATE%)"],
      "baseScore": 0,
      "scoringDistribution": "NORMAL",
      "type": ["number", "single", "absRange"],
      "range": 30
   },
   "composer": {
      "weight": 0,
      "tf": ["COMPOSER"],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["string", "multiple"]
   },
   "artistRegion": {
      "weight": 5,
      "tf": ["LOCALE LAST.FM"],
      "baseScore": 0,
      "scoringDistribution": "LOGISTIC",
      "type": ["string", "single", "virtual", "absRange", "tfRemap"],
      "range": 5
   },
   "genreStyleRegion": {
      "weight": 7,
      "tf": [],
      "baseScore": 0,
      "scoringDistribution": "LOGISTIC",
      "type": ["string", "single", "virtual", "absRange"],
      "range": 5
   },
   "Genre 2": {
      "weight": 0,
      "tf": [],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["multiple", "string", "graph"]
   },
   "Style 2": {
      "weight": 0,
      "tf": [],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["multiple", "string", "graph"]
   },
   "Region 2": {
      "weight": 0,
      "tf": [],
      "baseScore": 0,
      "scoringDistribution": "LINEAR",
      "type": ["multiple", "string", "graph"]
   }
}
``` 

</p>
</details> 

I found [line 173](https://github.com/regorxxx/Search-by-Distance-SMP/blob/115ae3aafeec6104ee70a3301a3944957bd24e0f/buttons/helpers/buttons_sbd_menu_config.js#L173) in the `buttons_sbd_menu_config.js` file.

If I remove the slash and the space before the `$1`, the new names are displayed correctly in the menu. But the two previous slots `Artist Region` and `Genre/Style Region` are displayed incorrectly (screenshot 5).

**Screenshots**

<details><summary>Screenshots</summary>
<p>

Screenshots 1, 2, 3:

![1](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/c977fdc5-75bb-49cb-872e-80c7d298b289)

![2](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/eda90ba4-5078-496c-b8fb-25766562ed7e)

![3](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/8179d02b-be12-45aa-91c7-dd286109a59e)

Screenshot 4:

![4](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/f0df18b2-ab1e-49ed-867a-b8b9e0afbad9)

Screenshot 5:

![5](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/f75cd195-09eb-492c-a89c-2fa4e2092b24)

</p>
</details> 

**Desktop**

 - OS: Windows 10
 - foobar2000 v2.1, new portable installation
 - Spider Monkey Panel v1.6.1 mod, new panel without settings
 - Search-by-Distance-SMP downloaded a few days ago, commit https://github.com/regorxxx/Search-by-Distance-SMP/commit/115ae3aafeec6104ee70a3301a3944957bd24e0f

**Comment by regorxxx** [comment]
Should be fixed now.

Sure it can still be broken on purpose, but should not produce errors anymore on trivial names.

**Comment by username116** [comment]
Yes, these tag names are displayed correctly in the menu now. Thank you.
