### ISSUE TITLE
[BUG] missing range property

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#29]
**Describe the bug**
I use a customizable button. I add a new custom tag. As in #19, this message appears:

```
Error on tags settings.
To fix it, restore defaults on affected tags (customizable button) or globally (non-customizable buttons). These options are usually found by Shift + L. Clicking on the button. Then reload the panel.
If the error continues, report it as a bug.
------------------------------------------------------------------------
Tag missing range property: My custom tag
```

**To reproduce**
1. With a customizable button, create a new tag
2. Enter a name for the tag: My custom tag
3. Is multi-valued? `No`
4. Are tag values strings? `No`
5. Uses absolute range? `No`
6. Uses percent range? `Yes`
7. See error

**Screenshot**
<details><summary>Screenshot</summary>
<p>

![1](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/99057938-450f-49f9-ba82-313fa292b827)

</p>
</details> 

**Additional context**

<details><summary>Tag properties in the "Edit tag..." menu</summary>
<p>

```json
{
  "weight": 0,
  "tf": [],
  "baseScore": 0,
  "scoringDistribution": "LINEAR",
  "type": ["single", "number", "percentRange"]
}
```

</p>
</details> 

New portable installation with default settings.

**System info**
 - OS: Windows 10 x64 22H2
 - Related software: foobar2000 v2.2 preview 2024-03-14 x86, Spider Monkey Panel v1.6.1-mod
 - Github release: Search-by-Distance-SMP v7.2.0

**Comment by regorxxx** [comment]
Fixed
