### ISSUE TITLE
[BUG] Recipe error

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#30]
**Describe the bug**
I use a customizable button. I create a recipe. When I run a search with this recipe, I get this error:
```
Error: Spider Monkey Panel v1.6.1-mod ({43278289-DA92-4882-9B7A-72C55888539A}: Playlist Tools: Buttons Bar v1.1.0 by regorxxx)
JSON.parse: unexpected character at line 1 column 1 of the JSON data

File: search_by_distance.js
Line: 895, Column: 31
Stack trace:
  searchByDistance@search_by_distance.js:895:31
  ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:81:5
  ThemedButton/this.onClick@buttons_xxx.js:604:21
  @buttons_xxx.js:964:21
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30
```

**To reproduce**
With a customizable button:
1. Ctrl + click: Create recipe file with current config
2. Enter Recipe name: my recipe
3. Include tag remapping? `Yes`
4. Also add additional variables? `Yes`
5. The folder opens, the file is created.
6. Ctrl + click: select "my recipe"
7. Click on the button to do a search
8. See error

**Screenshot**
<details><summary>Screenshot</summary>
<p>

![1](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/3d1717a2-69ac-4671-bf75-ba7406cd8919)

</p>
</details> 

**Additional context**
New portable installation with default settings.

[my recipe.json](https://github.com/regorxxx/Search-by-Distance-SMP/files/14812632/my.recipe.json)

<details><summary>Another error when the recipe is selected, with Shift + click on the button</summary>
<p>

```
Error: Spider Monkey Panel v1.6.1-mod ({43278289-DA92-4882-9B7A-72C55888539A}: Playlist Tools: Buttons Bar v1.1.0 by regorxxx)
JSON.parse: unexpected character at line 1 column 1 of the JSON data

File: buttons_sbd_menu_config.js
Line: 42, Column: 23
Stack trace:
  createTagMenu/<@buttons_sbd_menu_config.js:42:23
  createTagMenu@buttons_sbd_menu_config.js:39:11
  createConfigMenu@buttons_sbd_menu_config.js:372:4
  ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:60:4
  ThemedButton/this.onClick@buttons_xxx.js:604:21
  @buttons_xxx.js:964:21
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30
```

<details><summary>Screenshot</summary>
<p>

![2](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/5082283b-f9cb-4447-8ee0-0e62117122a6)

</p>
</details> 

</p>
</details> 

**System info**
 - OS: Windows 10 x64 22H2
 - Related software: foobar2000 v2.2 preview 2024-03-14 x86, Spider Monkey Panel v1.6.1-mod
 - Github release: Search-by-Distance-SMP v7.2.0

**Comment by regorxxx** [comment]
Fixed

**Comment by username116** [comment]
I tried the new version and it seems to work (for this one and also for #29), I don't get any more error messages.

Thanks!
