### ISSUE TITLE
[BUG] remove_duplicates.js

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#31]
Hi,

**Describe the bug**
I have an error after an update today. The error appears when I click on the button (customizable button) to launch a search.

On a new portable installation with Search-by-Distance 36a72321e75075e7a378370e51236568696e59a3, I get this:

```
Error: Spider Monkey Panel v1.6.1-mod ({598402E9-4AA5-4FA9-8FBC-9ABACC58FD3B}: Playlist Tools: Buttons Bar v1.1.0 by regorxxx)
dics[j] is undefined

File: remove_duplicates.js
Line: 312, Column: 69
Stack trace:
  removeDuplicates/</<@remove_duplicates.js:312:69
  removeDuplicates/<@remove_duplicates.js:312:49
  removeDuplicates@remove_duplicates.js:312:13
  searchByDistance@search_by_distance.js:1503:17
  ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:81:5
  ThemedButton/this.onClick@buttons_xxx.js:604:21
  @buttons_xxx.js:964:21
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30
```

<details><summary>Screenshot</summary>
<p>

![Screenshot](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/5d1f9447-182f-4cda-a1a9-46280050fdef)

</p>
</details> 

On my main installation with Search-by-Distance 7c61181548fb13bd6230cc6d458fa58c3cccc9a6, I had a different line number, but I'm not sure because there are also personal modifications:
<details><summary>Details</summary>
<p>

```
Error: Spider Monkey Panel v1.6.1-mod ({63AB1237-372D-479D-984F-84E3C32C3665}: Playlist Tools: Buttons Bar v1.1.0 by regorxxx)
dics[j] is undefined

File: remove_duplicates.js
Line: 326, Column: 69
Stack trace:
  removeDuplicates/</<@remove_duplicates.js:326:69
  removeDuplicates/<@remove_duplicates.js:326:49
  removeDuplicates@remove_duplicates.js:326:13
  searchByDistance@search_by_distance.js:1503:17
  ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:81:5
  ThemedButton/this.onClick@buttons_xxx.js:604:21
  @buttons_xxx.js:964:21
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30
```

<details><summary>Screenshot</summary>
<p>

![Screenshot](https://github.com/regorxxx/Search-by-Distance-SMP/assets/108369600/ffa6427a-b0f8-4126-b1dd-c644244f686a)

</p>
</details> 

If I go back to commit 611816e60c205723172b4a6b4af2b2e953e006cc on my main installation, there is no more error.

</p>
</details> 

**System info:**
 - OS: Windows 10 x64 22H2
 - Related software: foobar2000 v2.1.5 x86 (portable installation) / foobar2000 v2.2 preview 2024-03-14 x86
 - Github commit: 36a72321e75075e7a378370e51236568696e59a3 / 7c61181548fb13bd6230cc6d458fa58c3cccc9a6

**Comment by regorxxx** [comment]
EDIT: nevermind, try latest commit. Let me know if it works now. It probably was due to an error splitting a tag with '|' char, which didn't happen on my library.

**Comment by username116** [comment]
On the portable installation, this is the default setting:
``["$ascii($lower($trim($replace(%TITLE%,'',,`,,’,,´,,-,,\\,,/,,:,,$char(34),))))","%ALBUM ARTIST%","$year(%DATE%)"]``
On the main installation, I have buttons with the default setting, and other buttons with this setting:
`["%TITLE%","%ARTIST%","%ALBUM ARTIST%","%ALBUM%","$year(%DATE%)","%TRACKNUMBER%","%DIRECTORYNAME%"]`
I'm not sure what I'm doing. For the moment I want to see duplicate tracks in the playlist.
Three out of four buttons had errors yesterday.

With the latest commit c44c336eecf6a6bbe4d39d33456c665d839f95f7, I no longer have any errors, either on the portable installation or on the main installation.
Thanks for your modifications.

I did a quick comparison and found the same results as before if I deactivate the "Partial Multi-value tag matching" option. With this option enabled, I see changes in the playlists.

**Comment by regorxxx** [comment]
If you check the changelog, that option is the new default; but disabling it reverts the previous behavior. They are not supposed to output the same result in some cases.

Previously if there were multiple artists on a track, it required to match all of them (also on the same order) to consider another track as duplicate. Now it only requires a single match and doesn't care about the order. The new default should be more in line with regular users expectations.

So for [ARTIST, DATE, TITLE], these are duplicates with the new [default] option:

Jimi Hendrix - 1969 - blabla
Jimi Hendrix experience, Jimi Hendrix - 1969 - blabla
Band of Gypys, Jimi Hendrix - 1969 - blabla

While previously they were considered different tracks since not all artists matched.

**Comment by username116** [comment]
Thanks for the explanation.
