### ISSUE TITLE
[BUG] Menu with selected recipe

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#33]
**Describe the bug**
I create a recipe and select it (with the Ctrl menu).
Then I try to open the Shift + click menu.

```
Error: Spider Monkey Panel v1.6.1-mod ({436C553D-9DC7-49AF-9047-C311FEF2FCDB}: Playlist Tools: Buttons Bar v1.1.1 by regorxxx)
CheckMenuRadioItem failed:
Index is out of bounds

File: menu_xxx.js
Line: 465, Column: 34
Stack trace:
  _menu/this.checkMenu/<@menu_xxx.js:465:34
  _menu/this.initMenu/<@menu_xxx.js:586:4
  _menu/this.initMenu@menu_xxx.js:585:23
  _menu/this.btn_up@menu_xxx.js:617:30
  ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:60:27
  ThemedButton/this.onClick@buttons_xxx.js:604:21
  @buttons_xxx.js:964:21
  fireEvents/</<@callbacks_xxx.js:191:37
  fireEvents/<@callbacks_xxx.js:187:30
```

**To Reproduce**
1. In a new panel, load _buttons_toolbar.js_
2. Right-click to add a customizable button
3. Ctrl + click: Create recipe file with current config
4. Enter Recipe name: my recipe
5. Include tag remapping? `Yes`
6. Also add additional variables? `Yes`
7. The folder opens, the file is created.
8. Ctrl + click: select "my recipe"
9. Open Shift + click menu
10. See error

**Screenshot**

<details><summary>Screenshot</summary>
<p>

![Screenshot](https://github.com/user-attachments/assets/30dce5f8-0452-4e17-86a8-1876b7fbe29d)

</p>
</details> 

**System info:**
 - OS: Windows 10 x64 22H2
 - Related software: Foobar2000 v2.1.5 x86, new portable installation
 - Github release: Search-by-Distance commit 7df4ae90ce62958c987022bcb715a8c0b9fbbffe

**Comment by regorxxx** [comment]
Can not reproduce it, share the recipe file so I can test it please

**Comment by regorxxx** [comment]
> [20:57:48] this.checkMenu: entryB not found -> Artist cultural filter	[disabled]\Disabled
> [20:57:48] foo_spider_monkey_panel:
> Error: Spider Monkey Panel v1.6.1-mod (Playlist Tools: Playlist Tools: Buttons Bar v1.1.1 by regorxxx)
> CheckMenuRadioItem failed:
> Index is out of bounds
> 
> File: menu_xxx.js
> Line: 465, Column: 34
> Stack trace:
>   _menu/this.checkMenu/<@menu_xxx.js:465:34
>   _menu/this.initMenu/<@menu_xxx.js:586:4
>   _menu/this.initMenu@menu_xxx.js:585:23
>   _menu/this.btn_up@menu_xxx.js:617:30
>   ["Search by Distance Customizable"]<@buttons_search_by_distance_customizable.js:60:27
>   ThemedButton/this.onClick@buttons_xxx.js:604:21
>   @buttons_xxx.js:964:21
>   fireEvents/</<@callbacks_xxx.js:191:37
>   fireEvents/<@callbacks_xxx.js:187:30

Note in such cases the console reports more info, will fix it asap. Have been able to reproduce it.

**Comment by username116** [comment]
Ok, I'll try to remember. My console says the same thing:
`this.checkMenu: entryB not found -> Artist cultural filter	[disabled]\Disabled`

The recipe file:
[my recipe.json](https://github.com/user-attachments/files/16488655/my.recipe.json)

**Comment by username116** [comment]
The menu opens correctly now, with a recipe selected.
Thank you.

... and I think I've found another bug.
