### ISSUE TITLE
Remap tags menu errors

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#6]
I have an error in the Remap tags menu of the customizable button.

Ctrl + Shift + click  >  Remap tags  >  Set genre tag
Put `GENRE,STYLE` or `GENRE,A` for example, it doesn't matter. And OK.
See error.

'Set style tag' is concerned too.

```
Error: Spider Monkey Panel v1.6.1 (Search by Distance Customizable Button: Search by Distance Customizable Button by xxx)
scriptName is not defined

File: buttons_sbd_menu_config.js
Line: 377, Column: 21
Stack trace:
  func@buttons_sbd_menu_config.js:377:21
  _menu/this.btn_up/<@menu_xxx.js:305:15
  _menu/this.btn_up@menu_xxx.js:295:24
  ["Search by Distance Customizable"]<@buttons_search_bydistance_customizable.js:42:27
  themedButton/this.onClick@buttons_xxx.js:297:21
  @buttons_xxx.js:480:21
  fireEvents/</<@callbacks_xxx.js:148:37
  fireEvents/<@callbacks_xxx.js:145:30
```

![foobar2000](https://user-images.githubusercontent.com/108369600/197409818-55ba5ec0-41b3-4037-8745-55c6eefec97e.png)

This is a new button used alone, there was no other settings before. I tried with a new portable installation foobar2000 v2.0 beta 12 x86 + Spider Monkey Panel v1.6.1 + the current Search-by-Distance-SMP code downloaded today.

I see other errors in this menu, but maybe it's better to see them one by one in this report, if they are still present?

**Comment by regorxxx** [comment]
Fixed a few of those on the menu; I never saw them since I never loaded the button alone but within a toolbar with Playlist Tools, so variable was not missing.

**Comment by username116** [comment]
Thank you. The crashes are gone.
