### ISSUE TITLE
bTagsCache is not defined

### ISSUE THREAD

**Issue by username116** [regorxxx/Search-by-Distance-SMP#7]
I have an error with the customizable button.

- Load the script buttons_search_bydistance_customizable.js
- Wait for the console to display : Calculating tags 100%. Calculating graph links 100%.
- Name the button
- Select a track and click on the button.
- Wait 10 seconds.
- Error

```
Error: Spider Monkey Panel v1.6.1 (Search by Distance Customizable Button: Search by Distance Customizable Button by xxx)
bTagsCache is not defined

File: remove_duplicates.js
Line: 256, Column: 6
Stack trace:
  removeDuplicatesV3@remove_duplicates.js:256:6
  do_searchby_distance@search_bydistance.js:955:23
  async*["Search by Distance Customizable"]<@buttons_search_bydistance_customizable.js:58:5
  themedButton/this.onClick@buttons_xxx.js:297:21
  @buttons_xxx.js:480:21
  fireEvents/</<@callbacks_xxx.js:148:37
  fireEvents/<@callbacks_xxx.js:145:30
```

![Capture d'écran 129 foobar2000](https://user-images.githubusercontent.com/108369600/198017479-f006b2a3-b891-46e6-a961-362c34d114ea.png)

This is a new button used alone, there was no other settings before. I tried with a new portable installation foobar2000 v2.0 beta 12 x86 + Spider Monkey Panel v1.6.1 + the current Search-by-Distance-SMP code downloaded today.

Didn't you restore an old version?
https://github.com/regorxxx/Search-by-Distance-SMP/commit/56efb599f3e9ff9c4c975e952ba58daab003b625
https://github.com/regorxxx/Search-by-Distance-SMP/commit/e8cbbd521d3e51268f4e57f7c8094e8b19c72f75

I keep downloading the latest version because there is something I can't get to work with the previous version (add a custom tag in Genre with Graph method, I can make another report after this one if needed).

**Comment by regorxxx** [comment]
Yep, I accidentally deleted a variable on one of the latests commits. Just fixed it.

Tag remapping works fine for me though. I have been reworking a lot of things on the latest commits, so it's expected some things get broken meanwhile. Thanks for your help :)

**Comment by regorxxx** [comment]
Ok, found your problem. Thought I fixed all of those; only appears when loading a single button instead of using a toolbar (my use-case). Now definitely fixed

**Comment by username116** [comment]
Thank you,
This one (and #6 which has reappeared in the meantime) is fixed.

There is a new one, only with the Dyngenre method.
New portable installation, no setting, try directly the Dyngenre method after the cache calculation.

```
Error: Spider Monkey Panel v1.6.1 (Search by Distance Customizable Button: Search by Distance Customizable Button by xxx)
genre_style_map is not defined

File: search_bydistance.js
Line: 716, Column: 24
Stack trace:
  do_searchby_distance@search_bydistance.js:716:24
  ["Search by Distance Customizable"]<@buttons_search_bydistance_customizable.js:58:5
  themedButton/this.onClick@buttons_xxx.js:297:21
  @buttons_xxx.js:480:21
  fireEvents/</<@callbacks_xxx.js:148:37
  fireEvents/<@callbacks_xxx.js:145:30
```

![Capture d'écran 130 foobar2000 2](https://user-images.githubusercontent.com/108369600/198056937-6f94bc58-2908-477f-aef6-aa7b1aaa9027.png)

**Comment by regorxxx** [comment]
Done.

**Comment by username116** [comment]
Thank you, this one is also fixed.
